version: "3.9"

services:
  file_sharer_db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      ./docker/docker_env.env
  file_sharer:
    depends_on:
      - db
    image: file_sharer:latest
    expose:
      - 8080
    ports:
      - "${FILE_SHARER_PORT}:8080"
    restart: always
    env_file:
      ./docker/docker_env.env
volumes:
  db_data: {}