version: "3.7"

services:
  app:
    depends_on: [ db ]
    build: .
    container_name: file_sharer
    ports: [ "8080:33333" ]
    restart: always
    volumes: [ fs_data:/data ]
    env_file: docker/docker_env.env
    environment:
      - BUILDKIT_HOST=${BUILDKIT_HOST}
      - OKTETO_REGISTRY_URL=${OKTETO_REGISTRY_URL}
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: docker/docker_env.env
    ports: [ "20001:3306" ]
  migrations:
    build: .
    container_name: file_sharer_migrations
    command: file_sharer_migrations
    env_file: docker/docker_env.env
volumes:
  db_data: { }
  fs_data: { }