version: "3.7"

services:
  app:
    depends_on: [ db ]
    image: ghcr.io/goalt/filesharer:$IMAGE_VERSION
    container_name: file_sharer
    ports: [ "20002:33333" ]
    restart: always
    volumes: [ fs_data:/data ]
    env_file: .env
    environment:
      - SECRET_KEY=${FILE_SHARER_SECRET_KEY}
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env
    ports: [ "20001:3306" ]
  migrations:
    image: ghcr.io/goalt/filesharer:$IMAGE_VERSION
    container_name: file_sharer_migrations
    command: file_sharer_migrations
    env_file: .env
volumes:
  db_data: { }
  fs_data: { }