version: "3.7"

services:
  # app:
  #   depends_on: [db]
  #   image: file_sharer:latest
  #   container_name: file_sharer
  #   ports: [20000:8080]
  #   restart: always
  #   volumes: [fs_data:/data]
  #   env_file: docker_env.env
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: docker_env.env
    ports: [20001:3306]
  migrations:
    image: file_sharer:latest
    container_name: file_sharer_migrations
    command: file_sharer_migrations
    env_file: docker_env.env
volumes:
  db_data: {}
  fs_data: {}